// <auto-generated />
using System;
using Chatbot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatbot.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    [Migration("20260917192941_SeedInicial")]
    partial class SeedInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Chatbot.Domain.Chave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdGatilho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdGatilho");

                    b.ToTable("Chaves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGatilho = 1,
                            Texto = "horario"
                        },
                        new
                        {
                            Id = 2,
                            IdGatilho = 1,
                            Texto = "horas"
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Gatilho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gatilhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Horário"
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtendidoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdGatilho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroWhatsApp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("Chatbot.Domain.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdGatilho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdGatilho")
                        .IsUnique();

                    b.ToTable("Respostas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdGatilho = 1,
                            Texto = "Funcionamos de segunda a sexta, das 8h às 18h."
                        });
                });

            modelBuilder.Entity("Chatbot.Domain.Chave", b =>
                {
                    b.HasOne("Chatbot.Domain.Gatilho", null)
                        .WithMany("Chaves")
                        .HasForeignKey("IdGatilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chatbot.Domain.Resposta", b =>
                {
                    b.HasOne("Chatbot.Domain.Gatilho", null)
                        .WithOne("Resposta")
                        .HasForeignKey("Chatbot.Domain.Resposta", "IdGatilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chatbot.Domain.Gatilho", b =>
                {
                    b.Navigation("Chaves");

                    b.Navigation("Resposta")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
