// <auto-generated />
using System;
using Chatbot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatbot.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    partial class ChatbotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Chatbot.Domain.Chave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdGatilho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdGatilho");

                    b.ToTable("Chaves");
                });

            modelBuilder.Entity("Chatbot.Domain.Gatilho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gatilhos");
                });

            modelBuilder.Entity("Chatbot.Domain.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtendidoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdGatilho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroWhatsApp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("Chatbot.Domain.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdGatilho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdGatilho")
                        .IsUnique();

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("Chatbot.Domain.Chave", b =>
                {
                    b.HasOne("Chatbot.Domain.Gatilho", null)
                        .WithMany("Chaves")
                        .HasForeignKey("IdGatilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chatbot.Domain.Resposta", b =>
                {
                    b.HasOne("Chatbot.Domain.Gatilho", null)
                        .WithOne("Resposta")
                        .HasForeignKey("Chatbot.Domain.Resposta", "IdGatilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chatbot.Domain.Gatilho", b =>
                {
                    b.Navigation("Chaves");

                    b.Navigation("Resposta")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
